In [1]:
import pandas as pd
import numpy as np

In [47]:
from pathlib import Path

def afficher_arborescence(chemin=Path.cwd(), prefixe=""):
    chemin = Path(chemin)
    print(f"{prefixe}{chemin.name}/")
    elements = sorted(chemin.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))

    for i, element in enumerate(elements):
        dernier = i == len(elements) - 1
        branche = "└── " if dernier else "├── "
        print(f"{prefixe}{branche}{element.name}{'/' if element.is_dir() else ''}")
        #if element.is_dir():
        #    afficher_arborescence(element, prefixe + ("    " if dernier else "│   "))

afficher_arborescence()

DECC/
├── CAP INDUSTRIEL/
├── CAP STT/
├── INDUSTRIAL CAP/
├── TST CAP/
├── 2026_BEPC BILINGUE.xlsx
├── BEPC.csv
├── BEPC_BILINGUE.csv
├── CAP_INDUSTRIEL.csv
├── CAP_STT.csv
├── INDUSTRIAL_CAP.csv
├── Labo.ipynb
├── Sauvegarde de 2026_BEPC BILINGUE.xlk
├── TST_CAP.csv
└── ~$2026_BEPC_ADAMAOUA.xlsx

In [2]:
import pandas as pd
from pathlib import Path

RACINE = Path(r"C:\Users\LK\Desktop\DECC")

dataframes = {}

for dossier in RACINE.iterdir():
    
    print(dossier.name)

    if not dossier.is_dir():
        continue

    fichiers = list(dossier.rglob("*.xlsx"))

    tables = []

    for fichier in fichiers:
        try:
            df = pd.read_excel(fichier)
            tables.append(df)
            print(f"    {fichier} → {len(df)} lignes")
        except Exception as e:
            print(f"Erreur : {fichier} → {e}")

    if tables:

        df_final = pd.concat(
            tables,
            ignore_index=True,
            sort=False
        )

        dataframes[dossier.name] = df_final

        print(
            f"{dossier.name} : "
            f"{len(fichiers)} fichiers, "
            f"{len(df_final)} lignes"
        )

2026_BEPC BILINGUE.xlsx
BEPC.csv
CAP INDUSTRIEL
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_AFSC.xlsx → 64 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_AIBC.xlsx → 867 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_AICI.xlsx → 1054 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_CAPA.xlsx → 170 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_CARR.xlsx → 632 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_CHAR.xlsx → 204 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_COME.xlsx → 143601 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_COOM.xlsx → 4517 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_DEBA.xlsx → 886 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_DECOR.xlsx → 204 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_ELEQ.xlsx → 175060 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_ELME.xlsx → 1615 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_ELNI.xlsx → 5776 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_ESCO.xlsx → 958 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_FRCL.xlsx → 6201 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_INSA.xlsx → 8088 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MACO.xlsx → 211812 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MAEL.xlsx → 1312 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MAIN.xlsx → 0 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MARE.xlsx → 72188 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MEFA.xlsx → 2209 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MEFE.xlsx → 4091 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_MENU.xlsx → 43560 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_PA_PPO.xlsx → 303 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_PA_PVO.xlsx → 1513 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_PV_PCE.xlsx → 210 lignes
    C:\Users\LK\Desktop\DECC\CAP INDUSTRIEL\2026_CAP_IND_PV_PMA.xlsx → 1638 lignes
CAP INDUSTRIEL : 27 fichiers, 688733 lignes
CAP STT
    C:\Users\LK\Desktop\DECC\CAP STT\ESCOM.xlsx → 79922 lignes
    C:\Users\LK\Desktop\DECC\CAP STT\ESFI.xlsx → 240 lignes
    C:\Users\LK\Desktop\DECC\CAP STT\SEBU.xlsx → 12924 lignes
    C:\Users\LK\Desktop\DECC\CAP STT\SEME.xlsx → 14208 lignes
    C:\Users\LK\Desktop\DECC\CAP STT\VEND.xlsx → 1044 lignes
CAP STT : 5 fichiers, 108338 lignes
INDUSTRIAL CAP
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ABP.xlsx → 136 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ACV.xlsx → 1094 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\AEW.xlsx → 0 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ARM.xlsx → 9888 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\BEST.xlsx → 8129 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\BICA.xlsx → 929 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\BUCO.xlsx → 30277 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\CJ.xlsx → 3390 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ELM.xlsx → 0 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ELN.xlsx → 2033 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\EPS.xlsx → 22621 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\ESHD.xlsx → 34 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\INCA.xlsx → 30 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\MAME.xlsx → 929 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\PIS.xlsx → 2226 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\PTRY_PROD.xlsx → 128 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\SASH.xlsx → 0 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\SM.xlsx → 1487 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\TIL.xlsx → 377 lignes
    C:\Users\LK\Desktop\DECC\INDUSTRIAL CAP\WF.xlsx → 2317 lignes
INDUSTRIAL CAP : 20 fichiers, 86025 lignes
Labo.ipynb
TST CAP
    C:\Users\LK\Desktop\DECC\TST CAP\ASC.xlsx → 8763 lignes
    C:\Users\LK\Desktop\DECC\TST CAP\OA.xlsx → 2343 lignes
    C:\Users\LK\Desktop\DECC\TST CAP\SAL.xlsx → 878 lignes
TST CAP : 3 fichiers, 11984 lignes
~$2026_BEPC_ADAMAOUA.xlsx

In [3]:
#df_bepc=dataframes["BEPC"]
df_cap_indus=dataframes["CAP INDUSTRIEL"]
df_cap_stt=dataframes["CAP STT"]
df_indstrial_cap=dataframes["INDUSTRIAL CAP"]
df_tst_cap=dataframes["TST CAP"]

In [4]:
df_cap_indus.to_csv(r"C:\Users\LK\Desktop\DECC\CAP_INDUSTRIEL.csv", index=False)
df_cap_stt.to_csv(r"C:\Users\LK\Desktop\DECC\CAP_STT.csv", index=False)
df_indstrial_cap.to_csv(r"C:\Users\LK\Desktop\DECC\INDUSTRIAL_CAP.csv", index=False)
df_tst_cap.to_csv(r"C:\Users\LK\Desktop\DECC\TST_CAP.csv", index=False)

In [35]:
dataframes["INDUSTRIAL CAP"]

,LIBELLE_REGION,LIBELLE_DEPARTEMENT,LIBELLE_ETABLISSEMENT,LIBELLE_ORDRE_ENS,ABREVIATION_EXAMEN,LIBELLE_SERIE,NUM_CANDIDAT,ORDRE,CODE_MATIERE,LIBELLE_MATIERE,NOTE
0,NORTH-WEST,MEZAM,GTHS NKWEN,Public,INDUSTRIAL CAP,Automobile Bodywork and Painting,112179,1,PRACT,PRACTICAL WORKS,136
1,NORTH-WEST,MEZAM,GTHS NKWEN,Public,INDUSTRIAL CAP,Automobile Bodywork and Painting,112179,2,CPU_SCES_PRACT,COMPUTER SCIENCE PRACTICAL,16
2,NORTH-WEST,MEZAM,GTHS NKWEN,Public,INDUSTRIAL CAP,Automobile Bodywork and Painting,112179,3,INT_ SHIP,INTERNSHIP,20
3,NORTH-WEST,MEZAM,GTHS NKWEN,Public,INDUSTRIAL CAP,Automobile Bodywork and Painting,112179,4,ENG_LANG,ENGLISH LANGUAGE,26
4,NORTH-WEST,MEZAM,GTHS NKWEN,Public,INDUSTRIAL CAP,Automobile Bodywork and Painting,112179,5,FREN,FRENCH,4
...,...,...,...,...,...,...,...,...,...,...,...
86020,SUD,OCEAN,LYCEE TECHNIQUE BILINGUE KRIBI,Public,INDUSTRIAL CAP,Welding Fabrication,252677,13,TECHN,TECHNOLOGY,22
86021,SUD,OCEAN,LYCEE TECHNIQUE BILINGUE KRIBI,Public,INDUSTRIAL CAP,Welding Fabrication,252677,14,TRAC,TRACING,6
86022,SUD,OCEAN,LYCEE TECHNIQUE BILINGUE KRIBI,Public,INDUSTRIAL CAP,Welding Fabrication,252677,15,SPORT,SPORT AND PHYSICAL EDUCATION THEORY,32
86023,SUD,OCEAN,LYCEE TECHNIQUE BILINGUE KRIBI,Public,INDUSTRIAL CAP,Welding Fabrication,252677,16,OPT_PAPER,OPTIONAL PAPER,15
86024,SUD,OCEAN,LYCEE TECHNIQUE BILINGUE KRIBI,Public,INDUSTRIAL CAP,Welding Fabrication,252677,17,OPT_PAPER(Pts in +),OPTIONAL PAPER,5

In [36]:
df_tst_cap.columns.tolist()

['REGION',
 'DEPARTEMENT',
 'ETABLISSEMENT',
 'ORDRE_ENS',
 'SERIE',
 'NUM_CANDIDAT',
 'MATIERE',
 'NOTE']

In [39]:
df_bepc_bilin=pd.read_excel("2026_BEPC BILINGUE.xlsx")

In [48]:
df_cap_indus

,REGION,DEPARTEMENT,ETABLISSEMENT,ORDRE_ENS,SERIE,NUM_CANDIDAT,MATIERE,NOTE
0,LITTORAL,MOUNGO,LYCEE TECHNIQUE NKONGSAMBA I,Public,Affûteur-Scieur,88968,TRAVAUX PRATIQUES,136
1,LITTORAL,MOUNGO,LYCEE TECHNIQUE NKONGSAMBA I,Public,Affûteur-Scieur,88968,INFORMATIQUE PRATIQUE,17
2,LITTORAL,MOUNGO,LYCEE TECHNIQUE NKONGSAMBA I,Public,Affûteur-Scieur,88968,STAGE,30
3,LITTORAL,MOUNGO,LYCEE TECHNIQUE NKONGSAMBA I,Public,Affûteur-Scieur,88968,ETUDE DE TEXTE,24
4,LITTORAL,MOUNGO,LYCEE TECHNIQUE NKONGSAMBA I,Public,Affûteur-Scieur,88968,ANGLAIS,6
...,...,...,...,...,...,...,...,...
688728,SUD,OCEAN,COLLEGE TECHNIQUE ET PROFESSIONNEL AGRICOLE BI...,Public,Producteur de maraïchers,203577,TECHNIQUES CULTURALES DE MARAICHERS,58
688729,SUD,OCEAN,COLLEGE TECHNIQUE ET PROFESSIONNEL AGRICOLE BI...,Public,Producteur de maraïchers,203577,PROTECTION DES CULTURES MARAICHERES,36
688730,SUD,OCEAN,COLLEGE TECHNIQUE ET PROFESSIONNEL AGRICOLE BI...,Public,Producteur de maraïchers,203577,EDUCATION PHYSIQUE ET SPORTIVE,32
688731,SUD,OCEAN,COLLEGE TECHNIQUE ET PROFESSIONNEL AGRICOLE BI...,Public,Producteur de maraïchers,203577,EPREUVES FACULTATIVES,6
688732,SUD,OCEAN,COLLEGE TECHNIQUE ET PROFESSIONNEL AGRICOLE BI...,Public,Producteur de maraïchers,203577,EPREUVE FACULTATIVE,0

In [42]:
df_bepc_bilin=df_bepc_bilin[["LIBELLE_REGION","LIBELLE_DEPARTEMENT","LIBELLE_ETABLISSEMENT",
                             "LIBELLE_ORDRE_ENS","LIBELLE_SERIE","NUM_CANDIDAT","LIBELLE_MATIERE","NOTE"]]
df_bepc_bilin.columns=["REGION","DEPARTEMENT","ETABLISSEMENT",
                                "ORDRE_ENS","SERIE","NUM_CANDIDAT","MATIERE","NOTE"]

In [43]:
df_bepc_bilin.to_csv(r"C:\Users\LK\Desktop\DECC\BEPC_BILINGUE.csv", index=False)

In [46]:
afficher_arborescence()

DECC/
├── CAP INDUSTRIEL/
│   CAP INDUSTRIEL/
│   ├── 2026_CAP_IND_AFSC.xlsx
│   ├── 2026_CAP_IND_AIBC.xlsx
│   ├── 2026_CAP_IND_AICI.xlsx
│   ├── 2026_CAP_IND_CAPA.xlsx
│   ├── 2026_CAP_IND_CARR.xlsx
│   ├── 2026_CAP_IND_CHAR.xlsx
│   ├── 2026_CAP_IND_COME.xlsx
│   ├── 2026_CAP_IND_COOM.xlsx
│   ├── 2026_CAP_IND_DEBA.xlsx
│   ├── 2026_CAP_IND_DECOR.xlsx
│   ├── 2026_CAP_IND_ELEQ.xlsx
│   ├── 2026_CAP_IND_ELME.xlsx
│   ├── 2026_CAP_IND_ELNI.xlsx
│   ├── 2026_CAP_IND_ESCO.xlsx
│   ├── 2026_CAP_IND_FRCL.xlsx
│   ├── 2026_CAP_IND_INSA.xlsx
│   ├── 2026_CAP_IND_MACO.xlsx
│   ├── 2026_CAP_IND_MAEL.xlsx
│   ├── 2026_CAP_IND_MAIN.xlsx
│   ├── 2026_CAP_IND_MARE.xlsx
│   ├── 2026_CAP_IND_MEFA.xlsx
│   ├── 2026_CAP_IND_MEFE.xlsx
│   ├── 2026_CAP_IND_MENU.xlsx
│   ├── 2026_CAP_IND_PA_PPO.xlsx
│   ├── 2026_CAP_IND_PA_PVO.xlsx
│   ├── 2026_CAP_IND_PV_PCE.xlsx
│   └── 2026_CAP_IND_PV_PMA.xlsx
├── CAP STT/
│   CAP STT/
│   ├── ESCOM.xlsx
│   ├── ESFI.xlsx
│   ├── SEBU.xlsx
│   ├── SEME.xlsx
│   └── VEND.xlsx
├── INDUSTRIAL CAP/
│   INDUSTRIAL CAP/
│   ├── ABP.xlsx
│   ├── ACV.xlsx
│   ├── AEW.xlsx
│   ├── ARM.xlsx
│   ├── BEST.xlsx
│   ├── BICA.xlsx
│   ├── BUCO.xlsx
│   ├── CJ.xlsx
│   ├── ELM.xlsx
│   ├── ELN.xlsx
│   ├── EPS.xlsx
│   ├── ESHD.xlsx
│   ├── INCA.xlsx
│   ├── MAME.xlsx
│   ├── PIS.xlsx
│   ├── PTRY_PROD.xlsx
│   ├── SASH.xlsx
│   ├── SM.xlsx
│   ├── TIL.xlsx
│   └── WF.xlsx
├── TST CAP/
│   TST CAP/
│   ├── ASC.xlsx
│   ├── OA.xlsx
│   └── SAL.xlsx
├── 2026_BEPC BILINGUE.xlsx
├── BEPC.csv
├── BEPC_BILINGUE.csv
├── CAP_INDUSTRIEL.csv
├── CAP_STT.csv
├── INDUSTRIAL_CAP.csv
├── Labo.ipynb
├── Sauvegarde de 2026_BEPC BILINGUE.xlk
├── TST_CAP.csv
└── ~$2026_BEPC_ADAMAOUA.xlsx

In [2]:
import pandas as pd

In [14]:
data=pd.read_csv("data/TST_CAP.csv")
data=data[~data["MATIERE"].isin(["EPREUVE FACULTATIVE","OPTIONAL PAPER","EPREUVES FACULTATIVES","EPREUVE FACULTATIVE",
                                 "EPREUVES FACULATIVES","EPREUVES FACULTATIVES","EPREUVE FACULTATIVE",
                                 "OPTIONAL PAPER","OPTIONAL PAPERS","OPTIONAL PAPER"])]
data.to_csv("data/TST_CAP.csv", index=False)